name:    ${project.artifactId}
main:    ${project.groupId}.${project.artifactId}.BukkitPluginMain
version: ${project.version}
website: ${project.url}
author:  SimSonic
load:    STARTUP

softdepend:
- Vault
- WorldEdit
- WorldGuard

commands:
  rscp:
    aliases: [p]
    description: rscPermissions command hub
    usage: Enter /rscp help to see all subcommands

permissions:
  rscp.*:
    description: Gives access to all commands
    default: op
    children:
      rscp.admin: true
  rscp.admin:
    description: Allows you to use all /rscp subcommands
    default: op
    children:
      rscp.admin.lock: true
      rscp.admin.reload: true
      rscp.maintenance.*: true
      rscp.limits.*: true
  rscp.admin.lock:
    description: Allows to enable/disable maintenance modes
    default: op
  rscp.admin.reload:
    description: Allows to reload configuration and database
    default: op
  rscp.maintenance.*:
    description: Allows to connect when server is in any maintenance mode
    default: op
  rscp.limits.*:
    description: Allows to connect when server is reaching slot limit
    default: op
